### ISSUE TITLE
missing HR plot

### ISSUE THREAD

**Issue by DEEJCUK** [danielalvsaaker/tf-viewer#45] opened 2021-11-25 16:48 UTC
is the project still in development ?

just found this project and runing in docker, i import 2 .fit files converted from apple watch with heart rate, but not showing anything in the activity screen plot but is showing data in the sidebar 

    Activity type: Generic
    Duration: 00:49:12
    Max. heart rate: 148 bpm
    Avg. heart rate: 100 bpm
    Total calories: 332 kcal
    
    
![image](https://user-images.githubusercontent.com/32279047/143478670-edcf41da-fdae-4502-a7d1-00722e60b08c.png)

**Comment by danielalvsaaker** [comment] 2021-12-02 21:44
Still in development, just progressing very slowly due to studies and work. This issue and #46 is both caused by missing geographical data. I believe both should be fixed when I'm finally done with rewriting the whole stack.

**Comment by danielalvsaaker** [comment] 2022-02-17 11:23
This is a frontend issue, will be reopened later in a separate repository.

**Closed by danielalvsaaker** 2022-02-17 11:23 UTC
